#!/bin/bash

#######################################################################
#
# versions in this release

root_version=6.26.18
geant4_version=10.06.p02

#######################################################################

set -e

target_dir=$1

if [ "X$target_dir" = "X" ]; then
    echo "Please specify a target directory. Example: ./create-env /tmp/myenv" >&1
    exit 1
fi

if [ -e "$target_dir" ]; then
    echo "Target directory already exists - refusing to work on it" >&1
    exit 1
fi


function announce {
    echo
    echo "#######################################################################################"
    echo "## $1       ("`date -u`")"
    echo
}

# build environment
. /opt/XENONnT/setup.sh

export LC_ALL=en_US.utf8
export LANG=en_US.utf8

export PATH=$target_dir/bin:$PATH

for lib in /usr/lib64/libssl.so.10 /usr/lib64/libcrypto.so.10; do
    if [ ! -e "$lib" ]; then
        echo "Missing $lib. Install compat-openssl10 in the image." >&2
        exit 1
    fi
done

announce "Installing ROOT"
cd /tmp
wget -nv -O root_v${root_version}.Linux-AlmaLinux8.10-x86_64-gcc8.5.tar.gz https://root.cern/download/root_v${root_version}.Linux-AlmaLinux8.10-x86_64-gcc8.5.tar.gz
tar xzf root_v${root_version}.Linux-AlmaLinux8.10-x86_64-gcc8.5.tar.gz -C /opt
mv /opt/root $target_dir
rm -rf root_v${root_version}.Linux-AlmaLinux8.10-x86_64-gcc8.5.tar.gz

. ${target_dir}/bin/thisroot.sh
installed_root_version=$(root-config --version | tr '/' '.')
if [ "$installed_root_version" != "$root_version" ]; then
    echo "Unexpected ROOT version: $installed_root_version" >&2
    exit 1
fi

announce "Installing GEANT4"
set -v
cd /tmp
wget -nv -O geant4.${geant4_version}.tar.gz http://cern.ch/geant4-data/releases/geant4.${geant4_version}.tar.gz
tar xzf geant4.${geant4_version}.tar.gz
cd geant4.${geant4_version}
mkdir build 
cd build 
cmake -DCMAKE_INSTALL_PREFIX=$target_dir \
      -DGEANT4_INSTALL_DATA=ON \
      -DGEANT4_USE_OPENGL_X11=OFF \
      -DGEANT4_BUILD_MULTITHREADED=OFF \
      -DGEANT4_USE_QT=ON \
      -DGEANT4_USE_GDML=OFF \
      -DGEANT4_USE_RAYTRACER_X11=OFF \
      -DGEANT4_USE_XM=OFF \
      -DGEANT4_USE_HDF5=OFF \
      /tmp/geant4.${geant4_version}
make -j8
make install

# Geant4 10.06 still exports -std=c++11 in geant4make/geant4-config on EL8.
sed -i 's/-std=c++11/-std=c++17/g' "${target_dir}/bin/geant4-config"
sed -i 's/-std=c++11/-std=c++17/g' "${target_dir}"/share/Geant4-*/geant4make/config/sys/Linux-g++.gmk
sed -i 's/-std=c++11/-std=c++17/g' "${target_dir}"/lib*/Geant4-*/Geant4Config.cmake

# Fail early if the install still exports C++11
if "${target_dir}/bin/geant4-config" --cflags | grep -q -- '-std=c++11'; then
    echo "ERROR: Installed Geant4 still exports -std=c++11" >&2
    exit 1
fi

cd /tmp
rm -rf geant4.${geant4_version}.tar.gz geant4.${geant4_version}

# announce "Installing non-grid XENON software"
announce "Installing additional software not present in base_environment"
#python3 -m pip install numpy==1.22.4
#python3 -m pip install numba==0.55.2
#python3 -m pip install uproot==4.3.7
#python3 -m pip install awkward==1.10.1
#python3 -m pip install wfsim==1.2.2
#python3 -m pip install epix==0.3.8
#python3 -m pip install pema==0.7.0

# Cloning master branch of nestpy as of 12.02.2024
# Reason behind is that there is no new tag, while we need the last feature merged as of that date
#git clone https://github.com/NESTCollaboration/nestpy.git
#cd nestpy
#git submodule update --init --recursive
#git checkout 3b5ce87
#cd lib/pybind11
#git fetch --tags
#git checkout v2.13.0
#cd ../../
#sed -i 's/cmake_minimum_required(VERSION 2.8.12)/cmake_minimum_required(VERSION 2.8.12...3.30)/' CMakeLists.txt

#pip install .
#cd ..

#python3 -m pip install xenon-fuse==1.6.3

# hack to make thisroot.sh work in the minimal /bin/sh used
# when starting the Singularity container
cp /tmp/thisroot.sh ${target_dir}/bin/thisroot.sh

# this will be sourced when entering the container
cat > /.singularity.d/env/zzz-60-xenon-montecarlo.sh <<EOF
#!/bin/sh

if [ "x\$XENON_DEBUG" != "x" ]; then
    echo
    env
    echo
fi

if [ \$XENON_SOURCE -eq 1 ]; then
    START_DIR=\$PWD
    cd ${target_dir}/bin
    . ./thisroot.sh
    . ./geant4.sh
    cd ${target_dir}/share/Geant4-*/geant4make/
    . ./geant4make.sh
    cd \$START_DIR
fi
EOF

announce "All done!"
