#!/bin/bash

#######################################################################
#
# versions in this release

root_version=6.22.00
geant4_version=10.06.p02

#######################################################################

set -e

target_dir=$1

if [ "X$target_dir" = "X" ]; then
    echo "Please specify a target directory. Example: ./create-env /tmp/myenv" >&1
    exit 1
fi

if [ -e $target_dir ]; then
    echo "Target directory already exists - refusing to work on it" >&1
    exit 1
fi


function announce {
    echo
    echo "#######################################################################################"
    echo "## $1       ("`date -u`")"
    echo
}

# build environment
. /opt/XENONnT/setup.sh

export LC_ALL=en_US.utf8
export LANG=en_US.utf8

export PATH=$target_dir/bin:$PATH

announce "Installing ROOT"
cd /tmp
wget -nv -O root_v${root_version}.Linux-centos7-x86_64-gcc4.8.tar.gz  https://root.cern/download/root_v${root_version}.Linux-centos7-x86_64-gcc4.8.tar.gz
tar xzf root_v${root_version}.Linux-centos7-x86_64-gcc4.8.tar.gz -C /opt
mv /opt/root $target_dir
rm -rf root_v${root_version}.Linux-centos7-x86_64-gcc4.8.tar.gz

announce "Installing HDF5"
cd /tmp
wget -nv -O hdf5-1.10.6.tar.gz https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.6/src/hdf5-1.10.6.tar.gz
tar xzf hdf5-1.10.6.tar.gz
cd hdf5-1.10.6
./configure --prefix=$target_dir --enable-threadsafe --disable-hl
make -j4
make install
cd /tmp
rm -rf hdf5-1.10.6.tar.gz hdf5-1.10.6

announce "Installing GEANT4"
set -v
cd /tmp
wget -nv -O geant4.${geant4_version}.tar.gz http://cern.ch/geant4-data/releases/geant4.${geant4_version}.tar.gz
tar xzf geant4.${geant4_version}.tar.gz
cd geant4.${geant4_version}
mkdir build 
cd build 
cmake -DCMAKE_INSTALL_PREFIX=$target_dir \
      -DGEANT4_INSTALL_DATA=ON  \
      -DGEANT4_USE_OPENGL_X11=OFF \
      -DGEANT4_BUILD_MULTITHREADED=OFF \
      -DGEANT4_USE_QT=ON \
      -DGEANT4_USE_GDML=OFF \
      -DGEANT4_USE_RAYTRACER_X11=OFF \
      -DGEANT4_USE_XM=OFF \
      -DGEANT4_USE_HDF5=ON \
      /tmp/geant4.${geant4_version}
make -j8
make install
cd /tmp
rm -rf geant4.${geant4_version}.tar.gz geant4.${geant4_version}

# announce "Installing non-grid XENON software"
announce "Installing additional software not present in base_environment"
python3 -m pip install numpy==1.22.4
python3 -m pip install numba==0.57.0
python3 -m pip install uproot==5.0.7
python3 -m pip install awkward==2.2.1
#python3 -m pip install wfsim==1.0.2
python3 -m pip install epix==0.3.5

git clone https://github.com/AxFoundation/strax -b add_chunk_yielding_for_fuse
cd strax
pip install .
cd ..

# Cloning master branch of nestpy as of 28.09.2023
# Reason behind is that the v2.0.1 tag does not point to the v2.0.1 installation
git clone https://github.com/NESTCollaboration/nestpy.git
cd nestpy
git submodule update --init --recursive
pip install .
cd ..

# hack to make thisroot.sh work in the minimal /bin/sh used
# when starting the Singularity container
cp /tmp/thisroot.sh /opt/geant4/bin/thisroot.sh

# this will be sourced when entering the container
cat > /.singularity.d/env/zzz-60-xenon-montecarlo.sh <<EOF
#!/bin/sh

if [ "x\$XENON_DEBUG" != "x" ]; then
    echo
    env
    echo
fi

if [ \$XENON_SOURCE -eq 1 ]; then
    START_DIR=\$PWD
    cd ${target_dir}/bin
    . ./thisroot.sh
    . ./geant4.sh
    cd ${target_dir}/share/Geant4-*/geant4make/
    . ./geant4make.sh
    cd \$START_DIR
fi
EOF

announce "All done!"

